[data]
firstname="Thomas"
lastname="Durand"
age=18
languages=[ "French", "English", "Spanish"]
other=[ "Driving licence (soon)" ]
degree=[ "2 years CS degree" ]
skills=[ "C", "C++", "Java", "Python", "Rust (beginner)", "ASM" ]
hobbies=[ "Developping / programming", "Hacking", "3d modeling", "networks", "low-level"]
github="reede-dotpng"
linkedin="LinkedinUsername"
cv="rul"
pp="https://avatars.githubusercontent.com/u/42646590?s=460&u=787b5252e1c128be865794dba1e80ee5b3488634&v=4"