[data]
firstname="FirstName"
lastname="LastName"
age=18
languages=[ "English", "German"]
other=[ "Driving licence", "..."]
degree=[]
skills=["Javascript", "Python", "Java", "C#"]
hobbies=["Developping", "Designing", "Deploying"]
github="GithubPseudo"
linkedin="LinkedinUsername"
cv="url"
pp="http://www.newdesignfile.com/postpic/2011/03/unknown-person-with-question-mark_305280.jpg"