[data]
firstname="FirstName"
lastname="LastName"
age=18
languages=[ "English", "German"]
other=[ "Driving licence", "..."]
degree=[]
skills=["Javascript", "Python", "Java", "C#"]
hobbies=["Developping", "Designing", "Deploying"]
github="GithubPseudo"
linkedin="LinkedinUsername"
cv="url"
pp="https://avatars.githubusercontent.com/u/34798699?s=460&u=d7b3c05d7858d26b9a2a4d6e627296dd0dc28a1e&v=4"